// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashboardCard: typeof import('./../src/components/DashboardCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    ProBreadcrumb: typeof import('element-pro-components')['ProBreadcrumb']
    ProCard: typeof import('element-pro-components')['ProCard']
    ProColumnSetting: typeof import('element-pro-components')['ProColumnSetting']
    ProCrud: typeof import('element-pro-components')['ProCrud']
    ProForm: typeof import('element-pro-components')['ProForm']
    ProLayout: typeof import('element-pro-components')['ProLayout']
    ProTabs: typeof import('element-pro-components')['ProTabs']
    RichEditor: typeof import('./../src/components/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
