name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    if: ${{ github.repository_owner == 'tolking' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build:template

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.PAGE }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
